#!/bin/sh
set -eux

COSMO_LIBDIR=$(realpath "./libcosmo")
HEADER_PATHS=$(realpath "./header_stubs")
CC="${CC:-gcc}"

if [ ! -f $COSMO_LIBDIR/cosmopolitan.h ]; then
    echo "<<<SUPERCONFIGURE>>> cosmopolitan.h does not exist in $COSMO_LIBDIR!!!!"
    exit 1
fi

echo "<<<SUPERCONFIGURE>>> cosmopolitan.h exists in $COSMO_LIBDIR, assuming other files exist as well"

echo "<<<SUPERCONFIGURE>>> running buildconf "
./buildconf --force

# uncomment this line if 
# echo "<<<SUPERCONFIGURE>>> checking out configure just in case"
# git checkout -- ./configure

echo "<<<SUPERCONFIGURE>>> Running configure with $CC"
LD_LIBRARY_PATH="" ./configure \
    --enable-shared=no --enable-static=yes \
    --with-pic=no \
    --disable-ipv6 --without-pear \
    --without-pcre-jit --disable-all \
    --without-valgrind --disable-hash \
    --disable-phpdbg-debug --disable-debug \
    --enable-filter --enable-exif \
    --enable-ftp --enable-cgi \
    --with-zlib-dir="./" \
    CFLAGS="-Os \
    -Wall -Wno-implicit-fallthrough \
    -Wno-strict-prototypes -Wno-unused-value \
    -std=c99 -static \
    -fno-pie -no-pie \
    -fno-omit-frame-pointer \
    -ffunction-sections -fdata-sections \
    -mno-red-zone -pg \
    -nostdinc -nostdlib \
    -I$HEADER_PATHS \
    -include $COSMO_LIBDIR/cosmopolitan.h" \
    LDFLAGS="-static -nostdlib -nostdinc \
    -fno-pie -no-pie -mno-red-zone \
    -include $COSMO_LIBDIR/cosmopolitan.h" \
    LIBS="\
    -Wl,--gc-sections -fuse-ld=bfd \
    -Wl,-T,$COSMO_LIBDIR/ape.lds \
    -include $COSMO_LIBDIR/cosmopolitan.h \
    $COSMO_LIBDIR/crt.o \
    $COSMO_LIBDIR/ape.o \
    $COSMO_LIBDIR/cosmopolitan.a" 

echo "<<<SUPERCONFIGURE>>> Running make"
make -j4
